service: gpx-basic-stats-lambda-rest-endpoint

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs10.x

functions:
  geoStats:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get
